on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        make docker
        gzip -c dist/rootfs.ubi.sparse > dist/rootfs.ubi.sparse.gz
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo snap install hub --classic
        build_date=$(date +%Y%m%d)
        build_number=$[$(git tag | grep $build_date | wc -l) + 1]
        tag="$build_date.$build_number"
        hub release create $tag -m "$tag" -a dist/*.gz
